POST http://localhost:8080/patient
Content-Type: application/json

{
    "firstName":"test",
    "lastName":"test",
    "primary_email": "hariinfo@gmail.com"
}


###
GET http://localhost:8080/patient


###
GET http://localhost:8080/patient/15

###
GET http://localhost:8080/patient/dashboard/15


###
GET http://localhost:8080/appointment
{
    "patient_id":"15"
}