POST http://localhost:8080/patient
Content-Type: application/json

{
    "firstName":"test",
    "lastName":"test",
    "primary_email": "hariinfo@gmail.com"
}


###
GET http://localhost:80/patient


###
GET http://localhost:8080/patient/15

###
GET http://localhost:8080/patient/dashboard/15

###
GET http://localhost:8080/appointment/15

###
POST http://localhost:8080/appointment
Content-Type: application/json

{
    "patient_id":"15",
    "physician_id":1,
    "examination_room_id":1
}