version: "3"

services:

  varnish:
    image: varnish:latest
    volumes:
      - "../config/default.vcl:/etc/varnish/default.vcl"
    ports:
      - 8090:80
    depends_on:
      - frontend-a

  frontend-a:
    #Path to Dockerfile
    build: .
    #Image is only required when we don't have a Dockerfile
    #if we built the Docker file with this command docker build -t varnish-spring:1.0
    #image: varnish-spring:1.0
    hostname: frontend-a

    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dummy
      - SPRING_DATASOURCE_USERNAME=dummy
      - SPRING_DATASOURCE_PASSWORD=dummy

