create table if not exists appointment
(
    appointment_id INTEGER not null generated by default as identity primary key,
    patient_id INTEGER REFERENCES patient(patient_id),
    physician_id INTEGER REFERENCES physician(physician_id),
    examination_room_id INTEGER REFERENCES room(examination_room_id),
    start_dt_time TIMESTAMP,
    end_dt_time TIMESTAMP
);